---
- hosts: kib
  become: yes
  tasks:
    - name: kibana installation 
      apt:
        deb: http://mirror.yandex.ru/mirrors/elastic/7/pool/main/k/kibana/kibana-7.17.24-amd64.deb

    - name: copy kubana config
      template:
        src: /home/eugene/diplom/ansible/kibana.cfg
        dest: /etc/kibana/kibana.yml
    
    - name: demon reloading
      systemd_service:
        daemon_reload: true   

    - name: restart kibana
      service:
        name: kibana
        state: restarted
        enabled: true